-- MySQL Script generated by MySQL Workbench
-- Wed Oct  1 16:40:50 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
-- =====================================
-- User Table
-- =====================================
DROP TABLE IF EXISTS `User`;

CREATE TABLE `User` (
  `userId` INT NOT NULL AUTO_INCREMENT,
  `password` VARCHAR(255) NOT NULL,
  `phone` VARCHAR(10) NOT NULL,
  `createdAt` DATE NOT NULL,
  PRIMARY KEY (`userId`),
  UNIQUE (`phone`)
) ENGINE=InnoDB;

-- =====================================
-- Pet Table
-- =====================================
DROP TABLE IF EXISTS `Pet`;

CREATE TABLE `Pet` (
  `pId` INT NOT NULL AUTO_INCREMENT,
  `userId` INT NOT NULL,
  `age` INT NULL,
  `pName` VARCHAR(45) NOT NULL,
  `species` VARCHAR(45) NOT NULL,
  `weight` DECIMAL(5,2) NULL,
  `sex` ENUM('公', '母', '未知') NOT NULL,
  PRIMARY KEY (`pId`),
  INDEX `userId_idx` (`userId` ASC),
  CONSTRAINT `fk_pet_user` FOREIGN KEY (`userId`) REFERENCES `User`(`userId`) ON DELETE NO ACTION ON UPDATE CASCADE
) ENGINE=InnoDB;

-- =====================================
-- Disease Table
-- =====================================
DROP TABLE IF EXISTS `Disease`;

CREATE TABLE `Disease` (
  `diseaseId` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `description` VARCHAR(255) NULL,
  `severity` ENUM('低','中','高') DEFAULT '中',
  `advice` VARCHAR(255) DEFAULT '建議觀察情況，若惡化請就醫。',
  PRIMARY KEY (`diseaseId`)
) ENGINE=InnoDB;


-- =====================================
-- Conversation Table
-- =====================================
DROP TABLE IF EXISTS `Conversation`;

CREATE TABLE `Conversation` (
  `cId` INT NOT NULL AUTO_INCREMENT,
  `petId` INT NOT NULL,
  `diseaseId` INT NULL,
  `title` VARCHAR(255) NOT NULL,
  `severity` ENUM('低','中','高') NULL,
  `finalAdvice` VARCHAR(255) NULL,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`cId`),
  INDEX `petId_idx` (`petId` ASC),
  INDEX `diseaseId_idx` (`diseaseId` ASC),
  CONSTRAINT `fk_conversation_pet` FOREIGN KEY (`petId`) REFERENCES `Pet`(`pId`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_conversation_disease` FOREIGN KEY (`diseaseId`) REFERENCES `Disease`(`diseaseId`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB;

-- =====================================
-- Message Table
-- =====================================
DROP TABLE IF EXISTS `Message`;

CREATE TABLE `Message` (
  `messageId` BIGINT NOT NULL AUTO_INCREMENT,
  `conversationId` INT NOT NULL,
  `senderType` ENUM('User','AI') NOT NULL,
  `senderName` VARCHAR(45) NOT NULL,
  `content` TEXT NOT NULL,
  `timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`messageId`),
  INDEX `idx_conversationId` (`conversationId` ASC),
  CONSTRAINT `fk_message_conversation` FOREIGN KEY (`conversationId`) REFERENCES `Conversation`(`cId`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB;

-- =====================================
-- DiseaseAlias Table
-- =====================================
DROP TABLE IF EXISTS `DiseaseAlias`;

CREATE TABLE `DiseaseAlias` (
  `aliasId` INT NOT NULL AUTO_INCREMENT,
  `diseaseId` INT NOT NULL,
  `alias` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`aliasId`),
  INDEX `idx_diseaseId` (`diseaseId`),
  INDEX `idx_alias` (`alias`),
  CONSTRAINT `fk_disease_alias` FOREIGN KEY (`diseaseId`) REFERENCES `Disease`(`diseaseId`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO Disease (name, description, severity, advice) VALUES
('急性腸胃炎', '常因飲食不潔、病毒或細菌感染導致嘔吐與腹瀉。', '中', '建議禁食 12 小時並補充水分，若症狀持續請就醫。'),
('慢性腎衰竭', '腎功能逐漸喪失，常見於老年犬貓，會導致多飲多尿與體重下降。', '高', '需長期飲食控制與定期檢查。'),
('膀胱炎', '膀胱黏膜發炎，可能導致頻尿、血尿與排尿疼痛。', '中', '建議尿液檢查與抗生素治療。'),
('糖尿病', '胰島素分泌不足導致血糖過高，常見症狀為多飲多尿與體重下降。', '高', '需注射胰島素與飲食控制。'),
('甲狀腺機能亢進', '甲狀腺荷爾蒙過多，常見於老貓，會導致食慾增加與體重減輕。', '中', '建議服藥控制與定期追蹤。'),
('皮膚過敏', '對環境或食物過敏引起搔癢、紅疹與掉毛。', '低', '建議排除過敏源並使用抗敏藥物。'),
('耳炎', '耳道發炎，可能因細菌、黴菌或耳蟎引起，會導致搔癢與異味。', '中', '建議清潔耳道並使用藥物治療。'),
('椎間盤突出', '脊椎間軟骨突出壓迫神經，導致疼痛或癱瘓。', '高', '需影像診斷與休息，嚴重時需手術。'),
('心臟瓣膜病', '心臟瓣膜退化導致血液逆流，常見於小型犬。', '高', '需心臟超音波與藥物控制。'),
('肥胖症', '體重過重會增加關節與器官負擔，影響健康壽命。', '中', '建議飲食控制與增加運動。'),
('胰臟炎', '胰臟發炎會導致劇烈腹痛、嘔吐與食慾不振。', '高', '需禁食、靜脈輸液與住院治療。'),
('氣喘', '呼吸道慢性發炎導致呼吸困難與咳嗽，常見於貓。', '中', '建議使用支氣管擴張劑與避免過敏源。'),
('癲癇', '反覆性神經放電異常導致抽搐發作。', '高', '需長期服藥控制並監測發作頻率。'),
('皮膚黴菌感染', '由皮癬菌引起的皮膚病，會造成脫毛與紅疹。', '中', '建議使用抗黴菌藥物並隔離感染動物。'),
('異物誤食', '誤食異物可能造成腸阻塞或中毒。', '高', '需立即就醫，可能需手術取出。');

INSERT INTO DiseaseAlias (diseaseId, alias) VALUES
(1, '腸胃炎'),
(1, '胃腸炎'),
(2, '腎衰竭'),
(2, '慢性腎病'),
(3, '尿道感染'),
(3, '泌尿道感染'),
(4, '高血糖'),
(4, '胰島素不足'),
(5, '甲亢'),
(5, '甲狀腺亢進'),
(6, '過敏性皮膚炎'),
(6, '搔癢症'),
(7, '外耳炎'),
(7, '中耳炎'),
(8, '椎間盤病'),
(8, '脊椎壓迫'),
(9, '心臟病'),
(9, '瓣膜逆流'),
(10, '過重'),
(10, '體重過重'),
(11, '急性胰臟炎'),
(11, '胰腺炎'),
(12, '貓氣喘'),
(12, '支氣管炎'),
(13, '癲癇發作'),
(13, '抽搐'),
(14, '皮癬'),
(14, '黴菌感染'),
(15, '腸阻塞'),
(15, '誤食異物');

INSERT INTO disease (diseaseId, `name`, description)
VALUES (9999, 'AI 推論疾病', '尚未比對到資料庫疾病，為 AI 推論結果');